### ISSUE TITLE
Automatic Tailwind class name ordering

### ISSUE THREAD

**Issue by samjowen** [chrisgreg/bloom#6]
Hi Chris, first of all, great repo - love the idea.

Please may I suggest adding the Elixir [Tailwind formatter](https://github.com/100phlecs/tailwind_formatter) as a dependency to this project? It's designed to sort Tailwind classes, similar to the official Prettier Tailwind plugin, which you can read more about here: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier. 

The main benefits would be to enhance code readability and ensure style consistency across the project.

What do you think?

**Comment by chrisgreg** [comment]
I think that's a great idea - wanna raise a PR to implement it?

**Comment by samjowen** [comment]
> I think that's a great idea - wanna raise a PR to implement it?

Sure thing 👍
